language: cpp  # Just selected as a dummy.
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-pictures
      - texlive-science
      - latex-beamer
      - pgf
      #
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - lmodern

before_script:
  # Setup symbolic link to texmf folder
  - mkdir -p $HOME/texmf/tex
  - ln -s "${TRAVIS_BUILD_DIR}" "$HOME/texmf/tex/latex"

script:
  - cd "${TRAVIS_BUILD_DIR}/examples"
  - make
